using ReportDaemon;
using ReportManager.Services;
var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddSingleton<ConnectionService>();
builder.Services.AddScoped<ReportManagementService>();
builder.Services.AddScoped<FolderManagementService>();
builder.Services.AddScoped<DatabaseService>();
builder.Services.AddScoped<SharedService>();
builder.Services.AddScoped<EmailService>();
builder.Services.AddHostedService<Worker>();
var host = builder.Build();
host.Run();